# Generated by Django 4.2.1 on 2023-06-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_remove_loan_customer_loan_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='account',
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank_app.customer'),
        ),
    ]
