# Generated by Django 4.2.1 on 2023-06-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_loan_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bank_app.account'),
        ),
    ]
