# Generated by Django 4.2.1 on 2023-06-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_app.account'),
        ),
    ]
