# Generated by Django 4.2.1 on 2023-06-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_alter_payment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
